#!/bin/bash

if test $# == 0; then
    echo "Missing file to compile!"
else
    if java -cp antlr-4.7.2.jar:. SauroParser < $1 > Test.j; then
        if java -jar jasmin-2.4.jar Test.j; then
            java -cp . Test
        else
            rm -f Test.class
        fi
    else
        rm -f Test.j
    fi
fi
